<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pxl201001026" name="EMISION_TEST" tests="3" failures="1" timestamp="26 Aug 2015 17:33:59 GMT" time="30.17" errors="0">
  <testcase name="signOn" time="6.6" classname="com.praxis.ejem.test.smoke.SimpleSmokeTest"/>
  <testcase name="casoGenerarComprobante" time="12.58" classname="com.praxis.ejem.test.smoke.SimpleSmokeTest"/>
  <testcase name="casoPersonalizarComprobante" time="7.09" classname="com.praxis.ejem.test.smoke.SimpleSmokeTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Se gener贸 el comprobante exitosamente.&amp;gt; but was:&amp;lt;Confirmaci贸n&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Se gener贸 el comprobante exitosamente.> but was:<Confirmaci贸n>
	at com.praxis.ejem.test.smoke.SimpleSmokeTest.casoPersonalizarComprobante(SimpleSmokeTest.java:46)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:122)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
</testsuite>
